const Map<String, String> mapLanguage = {
  "hr-HR": "Croatian",
  "ko-KR": "Korean",
  "mr-IN": "Marathi",
  "ru-RU": "Russian",
  "zh-TW": "Chinese (Traditional)",
  "hu-HU": "Hungarian",
  "sw-KE": "Swahili",
  "th-TH": "Thai",
  "ur-PK": "Urdu",
  "nb-NO": "Norwegian",
  "da-DK": "Danish",
  "tr-TR": "Turkish",
  "et-EE": "Estonian",
  "pt-PT": "Portuguese (Portugal)",
  "vi-VN": "Vietnamese",
  "en-US": "English (US)",
  "sq-AL": "Albanian",
  "sv-SE": "Swedish",
  "ar": "Arabic",
  "su-ID": "Sundanese",
  "bn-BD": "Bengali (Bangladesh)",
  "bs-BA": "Bosnian",
  "gu-IN": "Gujarati",
  "kn-IN": "Kannada",
  "el-GR": "Greek",
  "hi-IN": "Hindi",
  "he-IL": "Hebrew",
  "fi-FI": "Finnish",
  "bn-IN": "Bengali (India)",
  "km-KH": "Khmer",
  "fr-FR": "French",
  "uk-UA": "Ukrainian",
  "pa-IN": "Punjabi (India)",
  "en-AU": "English (Australia)",
  "nl-NL": "Dutch",
  "fr-CA": "French (Canada)",
  "lv-LV": "Latvian",
  "sr": "Serbian",
  "pt-BR": "Portuguese (Brazil)",
  "de-DE": "German",
  "ml-IN": "Malayalam",
  "si-LK": "Sinhala",
  "cs-CZ": "Czech",
  "is-IS": "Icelandic",
  "pl-PL": "Polish",
  "ca-ES": "Catalan",
  "sk-SK": "Slovak",
  "it-IT": "Italian",
  "fil-PH": "Filipino",
  "lt-LT": "Lithuanian",
  "ne-NP": "Nepali",
  "ms-MY": "Malay",
  "en-NG": "English (Nigeria)",
  "nl-BE": "Dutch (Belgium)",
  "zh-CN": "Chinese (Simplified)",
  "es-ES": "Spanish (Spain)",
  "ja-JP": "Japanese",
  "ta-IN": "Tamil (India)",
  "bg-BG": "Bulgarian",
  "cy-GB": "Welsh",
  "yue-HK": "Cantonese (Hong Kong)",
  "es-US": "Spanish (United States)",
  "en-IN": "English (India)",
  "jv-ID": "Javanese",
  "id-ID": "Indonesian",
  "te-IN": "Telugu (India)",
  "ro-RO": "Romanian",
  "en-GB": "English (United Kingdom)"
};
